version: "3.7"
services:
  # PHP
  php:
    build:
      context: ./
      dockerfile: ./docker/php/image/Dockerfile
    image: slotegrator/php
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/config/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - slotegrator

  # MySQL
  mysql:
    image: mysql:5.7
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - slotegrator

  # Nginx
  nginx:
    image: nginx:alpine
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
    networks:
      - slotegrator

# Networks
networks:
  slotegrator:
    driver: bridge

# Volumes
# Volumes
volumes:
  mysql-data:
    driver: local
